name: Publish package to the Maven Central Repository
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build package
        run: cd sbom-demo-java && mvn package
      - name: Publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: sbom-demo-java/target/sbom-demo-app-1.0-SNAPSHOT-boot.jar
