name: Create S-Bom
on:
  workflow_dispatch:
  workflow_run:
    workflows: [Build]
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: AppThreat/cdxgen-action@v1
        with:
          output: "bom.xml"
          #serverUrl: "https://deptrack.appthreat.io"
          #apiKey: ${{ secrets.apiKey }}
      - run: |
          pwd
          ls -l
          ls -l sbom-demo-java
          ls -l sbom-demo-java/*        
      - uses: actions/upload-artifact@v1
        with:
          name: bom
          path: bom.xml
