name: Create S-Bom
on:
  workflow_dispatch:
  workflow_run:
    workflows: [Build]
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          cp -r sbom-demo-java/* .
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: AppThreat/cdxgen-action@v1
        with:
          output: "bom.xml"
          #serverUrl: "https://deptrack.appthreat.io"
          #apiKey: ${{ secrets.apiKey }}      
      - uses: actions/upload-artifact@v1
        with:
          name: bom
          path: bom.xml
